name: speed_share
description: 局域网共享文件客户终端.
publish_to: "none"

version: 2.2.8+68

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0
  tray_manager: ^0.2.0
  window_manager: ^0.3.0
  animations: ^2.0.2
  desktop_drop: ^0.4.1
  # dio_range_download: ^1.0.1
  clipboard_watcher: ^0.1.2
  signale: ^0.0.7
  file_selector: ^1.0.3
  # video preview
  better_player_plus: ^1.0.7
  get: ^4.1.3
  # animation
  simple_animations: ^5.0.0+3
  # qr code display
  qr_flutter: ^4.1.0
  open_file: ^3.2.1
  # scan qr code with camera
  mobile_scanner: ^6.0.2
  # file static serve
  shelf: ^1.3.0
  shelf_router: ^1.0.0
  shelf_proxy: ^1.0.0
  # svg display
  flutter_svg: ^1.1.0
  # open url
  url_launcher: ^6.0.4
  # file compress
  archive: ^3.1.2
  path: ^1.8.0
  image_picker: ^1.1.2
  # get file mime_type
  mime_type: ^1.0.0
  # http
  dio: ^5.4.3+1
  # responsive view
  responsive_framework: ^1.0.0
  path_provider: ^2.0.10
  device_info_plus: ^10.1.0
  # device find
  multicast:
    git: https://github.com/nightmare-space/multicast
  file_manager:
    git: https://github.com/nightmare-space/file_manager_private.git
  shelf_static:
    git:
      url: https://github.com/nightmare-space/shelf
      path: pkgs/shelf_static
  settings:
    git: https://github.com/nightmare-space/settings
  speed_share_extension:
    git:
      url: https://github.com/nightmare-space/empty_package
      path: speed_share_extension
  # global repository
  global_repository:
    git: https://github.com/nightmare-space/global_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  intl_utils: ^2.8.7

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - CHANGELOG.md
    - LICENSE

flutter_intl:
  enabled: true
